spring:
  mvc:
    static-path-pattern=+: /static/**
  web:
    resources:
      # spring ? ?? ?? ??? ?? ? ? ??? ?? ??
      static-locations: file:media/,classpath:/static

# ?? ?? ?? ( ?? 1MB )
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size : 10MB
